import React from "react";
import {
  Lightning,
  ShieldCheck,
  Code,
  Pulse,
  MagnifyingGlass,
  GridFour,
  BookOpen,
  Lock,
  Path,
  Broadcast,
  Cloud,
  HardDrives,
  Hexagon,
  TerminalWindow,
  Key,
  WindowsLogo,
  Cube,
  SquaresFour,
  Folder,
  Clock,
  PlugsConnected,
  Robot,
  Gauge,
  GearSix,
  Users,
  ListBullets,
  Play,
  Plus,
  ChartBar,
  Bell,
  SignOut,
  CaretRight,
  FileText,
  Check,
  Trash,
  PencilSimple,
  Envelope,
  Scales,
  ArrowRight,
  Eye,
  EyeSlash,
  Warning,
  Stop,
  ChatCircle,
  Sparkle,
  TreeStructure,
  Funnel,
  ArrowsSplit,
  Repeat,
  ArrowsClockwise,
  CodeBlock,
  ArrowsMerge,
  NotePencil,
  File,
  Wrench,
  X,
  CaretDown,
} from "@phosphor-icons/react";

/* AutoOps icon set — powered by Phosphor. Keep the <Icon name="..." /> API stable
   so every existing call site keeps working; only the visual style changes. */
const ICONS = {
  bolt: Lightning,
  shield: ShieldCheck,
  api: Code,
  pulse: Pulse,
  search: MagnifyingGlass,
  blocks: GridFour,
  book: BookOpen,
  lock: Lock,
  trail: Path,
  radar: Broadcast,
  cloud: Cloud,
  server: HardDrives,
  k8s: Hexagon,
  terminal: TerminalWindow,
  key: Key,
  azure: WindowsLogo,
  cube: Cube,
  dashboard: SquaresFour,
  folder: Folder,
  clock: Clock,
  webhook: PlugsConnected,
  robot: Robot,
  gauge: Gauge,
  gear: GearSix,
  users: Users,
  list: ListBullets,
  play: Play,
  plus: Plus,
  chart: ChartBar,
  bell: Bell,
  logout: SignOut,
  chevron: CaretRight,
  doc: FileText,
  check: Check,
  trash: Trash,
  pencil: PencilSimple,
  mail: Envelope,
  scale: Scales,
  "arrow-right": ArrowRight,
  eye: Eye,
  "eye-slash": EyeSlash,
  warning: Warning,
  // Workflow designer glyphs — one per node type so a palette and canvas can
  // tell node types apart at a glance (unknown names fall back to Lightning).
  stop: Stop,
  chat: ChatCircle,
  sparkles: Sparkle,
  branch: TreeStructure,
  filter: Funnel,
  split: ArrowsSplit,
  repeat: Repeat,
  refresh: ArrowsClockwise,
  code: CodeBlock,
  merge: ArrowsMerge,
  edit: NotePencil,
  file: File,
  wrench: Wrench,
  x: X,
  "chevron-down": CaretDown,
};

export default function Icon({
  name,
  size = 24,
  className = "",
  weight = "duotone",
}) {
  const Glyph = ICONS[name] || Lightning;
  return (
    <Glyph
      size={size}
      weight={weight}
      className={className}
      aria-hidden="true"
    />
  );
}
