"""The scope shapes agent-service must accept, produced by the real runtime.

**Why fixtures and not hand-written JSON on the Java side.** A Java test that
builds its own scope JSON tests what somebody *believed* the runtime emits. The
seam between the two services is exactly where that belief goes stale — a field
renamed here, a coverage value spelled differently, a digest computed over a
different canonical form — and both suites stay green while the contract breaks.

So these are generated by running ``extraction.extract`` and ``reduce._coverage``
over realistic tool output, written into agent-service's test resources, and
committed. This test asserts the runtime still produces exactly what is
committed; ``ScopeFixtureIT`` asserts agent-service still accepts it. Drift
fails on whichever side moved.

It also gets the cross-language digest agreement exercised on **real data**
rather than on vectors: the digest in each fixture is computed by Python here
and re-derived by Java there, from the same subject ids.

The three shapes are the ones that actually happen:

* two kinds both COMPLETE — the correlator's good day;
* one kind PARTIAL because one of its sources failed — the flagship failure,
  where coverage must survive for what WAS seen without claiming the rest;
* one kind SKIPPED entirely — every source for it failed.
"""

from __future__ import annotations

import json
import pathlib

from agent_runtime.app import reduce as reduce_module
from agent_runtime.app.extraction import SubjectSource
from agent_runtime.app.state import AgentState

#: Written into agent-service, because its tests run in a container that mounts
#: only that service — a single shared file is not reachable from both.
FIXTURES = (
    pathlib.Path(__file__).resolve().parents[2]
    / "agent-service" / "src" / "test" / "resources" / "scope-fixtures"
)

VOLUMES = SubjectSource("cloud_resource", "unattached_volumes", "{region}/{volume_id}")
EIPS = SubjectSource("cloud_resource", "unassociated_eips", "{region}/{allocation_id}")
USERS = SubjectSource("principal", "principals", "{account}/{user}")


def aws(**lists) -> str:
    return json.dumps({"region": "me-south-1", **lists})


def iam(**lists) -> str:
    return json.dumps({"account": "471112223334", **lists})


def coverage_for(*extractions) -> dict:
    """Runs the real fold: extractions -> per-kind scope elements + ids."""
    state = AgentState(agent_ref="aws.public_exposure_auditor", input="x")
    state.extractions = [
        {
            "subject_kind": e.subject_kind,
            "outcome": e.outcome.value,
            "subject_ids": list(e.subject_ids),
            "source_total": e.source_total,
            "reason": e.reason,
        }
        for e in extractions
    ]
    elements, ids = reduce_module._coverage(state)
    return {"subject_scope": elements, "subject_ids": ids}


def extract(content, source, ok=True):
    from agent_runtime.app.extraction import extract as run

    return run(content, source, tool_ok=ok)


def build() -> dict[str, dict]:
    buckets = aws(unattached_volumes=[{"volume_id": "vol-1"}, {"volume_id": "vol-2"}])
    eips = aws(unassociated_eips=[{"allocation_id": "eipalloc-1"}])
    users = iam(principals=[{"user": "ali.hassan"}, {"user": "svc-deploy"}])

    return {
        # The correlator's good day: cloud_resource from two sources, principal
        # from one, everything read.
        "two-kinds-complete": coverage_for(
            extract(buckets, VOLUMES),
            extract(eips, EIPS),
            extract(users, USERS),
        ),
        # THE case the whole per-element design exists for. The EIP listing
        # threw; volumes were read. cloud_resource keeps the volumes it really
        # saw and drops to PARTIAL, so nothing reaps an elastic IP finding on
        # evidence that never looked at an elastic IP. principal is untouched.
        "one-kind-partial": coverage_for(
            extract(buckets, VOLUMES),
            extract("DescribeAddresses threw", EIPS, ok=False),
            extract(users, USERS),
        ),
        # Every source for a kind failed. Not PARTIAL — PARTIAL over nothing is
        # a claim shaped like coverage with no coverage behind it.
        "one-kind-skipped": coverage_for(
            extract(buckets, VOLUMES),
            extract(eips, EIPS),
            extract("Graph returned 403", USERS, ok=False),
        ),
    }


def test_the_committed_fixtures_match_what_the_runtime_produces():
    """Regenerate with ``pytest -k fixtures --regenerate`` is deliberately NOT
    offered: a fixture that regenerates on demand records whatever the code does
    today, which is the opposite of a contract. If this fails, either the change
    was intended — update the file and the Java test together, in one commit —
    or the runtime just broke the seam.
    """
    for name, expected in build().items():
        path = FIXTURES / f"{name}.json"
        assert path.exists(), f"missing fixture {path}; write it from build()"
        assert json.loads(path.read_text(encoding="utf-8")) == expected, name


def test_the_partial_shape_keeps_what_was_seen():
    """The assertion the fixture exists to carry, stated once in Python too."""
    shapes = build()["one-kind-partial"]["subject_scope"]
    resources = next(e for e in shapes if e["subject_kind"] == "cloud_resource")

    assert resources["coverage"] == "PARTIAL"
    assert resources["subject_id_count"] == 2, "the volumes it really saw survive"

    principals = next(e for e in shapes if e["subject_kind"] == "principal")
    assert principals["coverage"] == "COMPLETE", "one kind failing does not cost another"


def test_skipped_claims_nothing_at_all():
    shapes = build()["one-kind-skipped"]["subject_scope"]
    principals = next(e for e in shapes if e["subject_kind"] == "principal")

    assert principals["coverage"] == "SKIPPED"
    assert principals["subject_id_count"] == 0


# ------------------------------------------------- verdicts, from the real path ---


def verdict_fixture() -> dict:
    """Two verdicts as ``verdicts.verdicts`` really renders them.

    Generated rather than hand-written for the same reason the scope fixtures
    are: agent-service's ordering test needs to ingest what the runtime ACTUALLY
    emits, not what somebody believed it emits. One names a subject and gets a
    stable key; one does not and is honestly marked unstable, because ingest
    refuses those and a test that never sees one would not prove it.
    """
    from agent_runtime.app import verdicts as verdicts_module
    from agent_runtime.app.state import Finding

    state = AgentState(agent_ref="aws.incident_rca_analyst", input="why did checkout page?")
    state.findings = [
        Finding(
            summary="cpu-high has flapped 14 times in the window.",
            severity="warning",
            subject_kind="alert_rule",
            subject_id="me-south-1/cpu-high",
            finding_type="flapping_alarm",
            evidence_ids=[1],
        ),
        Finding(
            summary="The incident correlates with a deploy, but no single subject.",
            severity="info",
            evidence_ids=[1],
        ),
    ]
    return {
        "findings": verdicts_module.verdicts(
            state,
            agent_ref="aws.incident_rca_analyst",
            agent_version="1.0.0",
            run_id=None,
            tenant_id=None,
            window="2026-09-20",
            has_mutating=False,
        )
    }


def test_the_verdict_fixture_matches_what_the_runtime_produces():
    path = FIXTURES / "verdicts.json"
    assert path.exists(), f"missing fixture {path}"

    expected = verdict_fixture()
    actual = json.loads(path.read_text(encoding="utf-8"))

    # verdict_id is compared like everything else: it is DERIVED, so a change
    # to how it is derived is a contract change agent-service must see.
    assert actual == expected


def test_a_verdict_id_is_stable_across_calls():
    """Replay protection depends on it.

    agent-service refuses a verdict id it has already stored — that is how a
    network retry stops becoming a second sighting and inflating every counter.
    A random id would be fresh on every retry and each one would store, which is
    the single easiest way to make every number here lie.
    """
    first = [v["verdict_id"] for v in verdict_fixture()["findings"]]
    second = [v["verdict_id"] for v in verdict_fixture()["findings"]]

    assert first == second
    assert len(set(first)) == 2, "and distinct per finding within a run"


def test_the_ingest_contract_fields_are_all_present():
    """The mismatch this fixture caught.

    agent-service rejects a verdict with no ``verdict_id`` before it looks at
    anything else — and the runtime was not emitting one. Every verdict would
    have been refused, findings would have stayed at zero, and the attribution
    counters would have stayed EMPTY, because the rejection happens before
    attribution is recorded. All-zero counters from a contract mismatch look
    exactly like all-zero counters from nothing having run.
    """
    for verdict in verdict_fixture()["findings"]:
        for required in ("verdict_id", "idempotency_key", "stable_key", "agent",
                         "subject", "finding"):
            assert required in verdict, required
        assert verdict["agent"].get("name")


def test_one_verdict_is_stable_and_one_is_honestly_not():
    found = verdict_fixture()["findings"]

    assert [v["stable_key"] for v in found] == [True, False]


def test_recomputing_from_the_same_state_yields_the_same_verdict_ids():
    """The retry path, pinned.

    agent-service re-POSTs a payload whose id is already in it, so that case is
    stable by construction. The one worth asserting is a reduce called again
    over the same persisted state: it must recompute identical ids, or replay
    protection stops recognising the retry and every attempt stores again.

    Nothing in the runtime sorts ``state.findings`` — this is what fails if
    something starts to.
    """
    from agent_runtime.app import verdicts as verdicts_module
    from agent_runtime.app.state import Finding

    def emit():
        state = AgentState(agent_ref="a", input="x")
        state.findings = [
            Finding(summary="one", severity="warning", subject_kind="alert_rule",
                    subject_id="r1", finding_type="t"),
            Finding(summary="two", severity="warning", subject_kind="alert_rule",
                    subject_id="r2", finding_type="t"),
        ]
        return [v["verdict_id"] for v in verdicts_module.verdicts(
            state, agent_ref="a", agent_version="1", run_id=77,
            tenant_id="t", window="2026-09-20", has_mutating=False)]

    assert emit() == emit()
    assert len(set(emit())) == 2
