package com.intertec.autoops.agent.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.intertec.autoops.agent.MySqlTestDatabase;
import com.intertec.autoops.agent.domain.Agent;
import com.intertec.autoops.agent.domain.AgentRun;
import com.intertec.autoops.agent.repo.AgentRepository;
import com.intertec.autoops.agent.repo.AgentRunRepository;
import com.intertec.autoops.agent.repo.FindingRepository;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.ImportAutoConfiguration;
import org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verdicts must be filed while the run is still open.
 *
 * <p><b>What this proves, and what it does not.</b> It proves the ORDER in
 * which {@code AgentRunService} files verdicts, settles coverage and finishes a
 * run — deterministically, including the negative. It proves nothing about an
 * estate: subject counts against reality, composed ids on real tool output, and
 * digest agreement on non-fixture data all still need working cloud credentials
 * and a declared {@code SubjectSource}, and remain unverified. A green suite
 * here is not an end-to-end verification, and reading it as one is the mistake
 * this paragraph exists to prevent.
 *
 * <p><b>Why it is better than a live run for this question.</b> A live run can
 * only show that {@code late} happens to be zero. Here the failure is
 * constructed: settle the scope first and watch every verdict be refused, which
 * is the evidence that the ordering is load-bearing rather than incidental.
 *
 * <p><b>The boundary is narrower than it looks.</b>
 * {@code VerdictAttributionService} treats a run as closed the moment
 * {@code scope_status} leaves RUNNING — not when {@code finished_at} is set. So
 * the window for filing verdicts closes at {@code completeScope}, and a
 * plausible-looking placement between completing and finishing fails exactly as
 * badly as one after finishing. The symptom in both cases is
 * {@code run_already_completed}, a reason code meaning "the agent raced its own
 * completion", which sends the investigation after agent timing while the cause
 * sits in three lines of service code.
 *
 * <p>The verdicts come from {@code scope-fixtures/verdicts.json}, generated by
 * running the runtime's real {@code verdicts.verdicts()} — so this ingests what
 * agent-runtime actually emits rather than what somebody believed it emits.
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ImportAutoConfiguration(FlywayAutoConfiguration.class)
@Import({RunScopeService.class, VerdictAttributionService.class, FindingIngestService.class,
        RunScopeServiceTest.Beans.class})
class RunCompletionOrderIT {

    private static final String TENANT = "acme";
    private static final Long PROJECT = 9L;
    private static final String AGENT = "aws.incident_rca_analyst";

    private static MySqlTestDatabase database;

    @DynamicPropertySource
    static void datasource(DynamicPropertyRegistry registry) throws Exception {
        database = MySqlTestDatabase.start();
        registry.add("spring.datasource.url", database::url);
        registry.add("spring.datasource.username", database::user);
        registry.add("spring.datasource.password", database::password);
        registry.add("spring.datasource.driver-class-name", () -> "com.mysql.cj.jdbc.Driver");
        registry.add("spring.flyway.enabled", () -> true);
        registry.add("spring.jpa.hibernate.ddl-auto", () -> "none");
    }

    @AfterAll
    static void release() throws Exception {
        database.close();
    }

    @Autowired
    private RunScopeService scopes;
    @Autowired
    private FindingIngestService ingest;
    @Autowired
    private VerdictAttributionService attributions;
    @Autowired
    private AgentRepository agents;
    @Autowired
    private AgentRunRepository runs;
    @Autowired
    private FindingRepository findings;
    @Autowired
    private JdbcTemplate jdbc;
    @Autowired
    private TestEntityManager entities;

    private final ObjectMapper mapper = new ObjectMapper();
    private Long runId;

    @BeforeEach
    void setUp() {
        jdbc.update("DELETE FROM finding_observations");
        jdbc.update("DELETE FROM finding_transitions");
        jdbc.update("DELETE FROM findings");
        jdbc.update("DELETE FROM verdict_attribution_daily");
        jdbc.update("DELETE FROM agent_run_subject");
        jdbc.update("DELETE FROM agent_runs");
        jdbc.update("DELETE FROM agents");

        Agent agent = new Agent();
        agent.setTenantId(TENANT);
        agent.setProjectId(PROJECT);
        agent.setName(AGENT);
        Long agentId = agents.save(agent).getId();

        AgentRun run = new AgentRun();
        run.setTenantId(TENANT);
        run.setProjectId(PROJECT);
        run.setAgentId(agentId);
        run.setInput("{}");
        run.setStatus(AgentRun.Status.RUNNING);
        run.setStartedAt(Instant.now());
        runId = runs.save(run).getId();
        sync();
    }

    private void sync() {
        entities.flush();
        entities.clear();
    }

    private JsonNode fixture(String name) {
        try (var stream = new ClassPathResource("scope-fixtures/" + name + ".json")
                .getInputStream()) {
            return mapper.readTree(stream);
        } catch (Exception e) {
            throw new AssertionError("fixture " + name + " missing", e);
        }
    }

    private List<JsonNode> verdicts() {
        List<JsonNode> out = new ArrayList<>();
        fixture("verdicts").get("findings").forEach(out::add);
        return out;
    }

    /** What {@code AgentRunService.ingestVerdicts} does, minus the logging. */
    private int fileAll() {
        int accepted = 0;
        for (JsonNode verdict : verdicts()) {
            if (ingest.ingest(TENANT, PROJECT, runId, verdict).disposition()
                    != FindingIngestService.Disposition.REJECTED) {
                accepted++;
            }
        }
        sync();
        return accepted;
    }

    private void settleScope(int emitted) {
        JsonNode payload = fixture("two-kinds-complete");
        Map<String, Integer> evaluated = new LinkedHashMap<>();
        payload.get("subject_scope").forEach(element ->
                evaluated.put(element.get("subject_kind").asText(),
                        element.get("subject_id_count").asInt()));

        var intent = mapper.createArrayNode();
        evaluated.keySet().forEach(kind ->
                intent.addObject().put("kind", "all").put("subject_kind", kind));
        scopes.declare(runId, intent, Map.of());
        sync();

        Map<String, List<String>> ids = new LinkedHashMap<>();
        payload.get("subject_ids").fields().forEachRemaining(entry -> {
            List<String> values = new ArrayList<>();
            entry.getValue().forEach(id -> values.add(id.asText()));
            ids.put(entry.getKey(), values);
        });
        scopes.complete(runId, payload.get("subject_scope"), ids, evaluated, emitted);
        sync();
    }

    private VerdictAttributionService.Attributed counters() {
        return attributions.byAgent(TENANT, LocalDate.now(ZoneOffset.UTC)).stream()
                .filter(row -> row.agentName().equals(AGENT))
                .findFirst()
                .orElseThrow(() -> new AssertionError("no attribution row"));
    }

    // ------------------------------------------------------- the right order ---

    @Test
    void verdictsFiledBeforeTheScopeSettlesAreAccepted() {
        int accepted = fileAll();
        settleScope(accepted);

        assertThat(findings.count())
                .as("the subject-naming verdict landed")
                .isEqualTo(1);

        VerdictAttributionService.Attributed counts = counters();
        assertThat(counts.late())
                .as("the negative this test exists for")
                .isZero();
        assertThat(counts.foreignRun()).isZero();
        assertThat(counts.unattributed()).isZero();

        assertThat(runs.findById(runId).orElseThrow().getVerdictsEmitted())
                .as("ACCEPTED, not attempted — a run that emitted nothing because "
                        + "everything was refused is not a clean estate")
                .isEqualTo(1);
    }

    /**
     * The subject-less verdict is refused, and that is not a failure of this
     * path.
     *
     * <p>A finding that names no single subject has nothing stable to hash, so
     * the runtime marks it {@code stable_key: false} rather than inventing a key
     * that would re-file the same thing nightly and never be dismissible.
     */
    @Test
    void aVerdictWithNoStableKeyIsRefusedWithoutAffectingTheOthers() {
        assertThat(fileAll()).isEqualTo(1);
        assertThat(findings.count()).isEqualTo(1);
    }

    // ------------------------------------------------------- the wrong order ---

    /**
     * <b>The constructed failure.</b>
     *
     * <p>Settling the scope first — which is what moving {@code ingestVerdicts}
     * below {@code completeScope} would do — refuses every verdict, because the
     * run is already closed for attribution. A live run could only ever show
     * that {@code late} happened to be zero; this shows what makes it zero.
     */
    @Test
    void verdictsFiledAfterTheScopeSettlesAreAllRefusedAsLate() {
        settleScope(0);

        for (JsonNode verdict : verdicts()) {
            FindingIngestService.Result result = ingest.ingest(TENANT, PROJECT, runId, verdict);
            assertThat(result.disposition())
                    .isEqualTo(FindingIngestService.Disposition.REJECTED);
        }
        sync();

        assertThat(findings.count())
                .as("nothing was stored — the whole run's output would be lost")
                .isZero();
        // ONE, not two. The subject-less verdict is refused for having no
        // stable key BEFORE attribution is consulted, so it never reaches the
        // late counter at all — a timing counter should not move for a verdict
        // refused on its content. Only the verdict that would otherwise have
        // been stored reads as late, and that is the one whose loss matters.
        assertThat(counters().late())
                .as("and it reads as the agent racing itself, not as a service bug")
                .isEqualTo(1);
    }

    /**
     * The same refusal arrives after {@code finish()} too — so a placement
     * BETWEEN completing and finishing is not a safe middle ground.
     */
    @Test
    void theWindowClosesAtCompleteScopeNotAtFinish() {
        settleScope(0);
        AgentRun run = runs.findById(runId).orElseThrow();
        assertThat(run.getFinishedAt())
                .as("not finished yet — and the window is already shut")
                .isNull();

        assertThat(ingest.ingest(TENANT, PROJECT, runId, verdicts().getFirst()).reasonCode())
                .isEqualTo("run_already_completed");
    }
}
