package com.intertec.autoops.agent.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.intertec.autoops.agent.domain.Agent;
import com.intertec.autoops.agent.domain.AgentRun;
import com.intertec.autoops.agent.exception.AgentException;
import com.intertec.autoops.agent.repo.AgentRepository;
import com.intertec.autoops.agent.repo.AgentRunRepository;
import com.intertec.autoops.agent.scope.RunScope;
import com.intertec.autoops.agent.scope.ScopeClaim;
import com.intertec.autoops.agent.MySqlTestDatabase;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.autoconfigure.ImportAutoConfiguration;
import org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * The seam, exercised against what agent-runtime actually emits.
 *
 * <p><b>Why fixtures rather than JSON written here.</b> A test that builds its
 * own scope document tests what somebody <i>believed</i> the runtime emits, and
 * the seam between two services is exactly where that belief goes stale — a
 * renamed field, a coverage value spelled differently, a digest over a different
 * canonical form. Both suites stay green while the contract breaks.
 *
 * <p>So {@code src/test/resources/scope-fixtures/*.json} is generated by running
 * the real extraction and fold in agent-runtime, and
 * {@code tests/test_scope_fixtures.py} asserts the runtime still produces
 * exactly those bytes. This asserts agent-service still accepts them. Drift
 * fails on whichever side moved.
 *
 * <p>It also puts the cross-language digest agreement on <b>real data</b> for
 * the first time: the digests in these files were computed by Python, and
 * {@link RunScopeService} recomputes them here from the same subject ids. Every
 * previous test of that agreement used vectors.
 *
 * <p><b>An IT rather than a unit test, because H2 gets this wrong.</b> Given a
 * {@code JSON} column and a String, MySQL parses it — {@code JSON_TYPE} returns
 * {@code ARRAY} and a read gives the array back. H2 wraps the string as a JSON
 * <i>string literal</i>, so a re-read yields one long quoted string and every
 * scope becomes unparseable. Production is correct; the harness was lying, and
 * it surfaced only here because this is the first test that clears the
 * persistence context between declare and complete and therefore actually
 * re-reads the column.
 *
 * <p>That is the fourth time {@code @DataJpaTest} has diverged from production
 * in a way that made a test WRONG rather than absent — after Hibernate DDL
 * instead of Flyway, the unflushed persistence context, and the missing
 * {@code ObjectMapper}. The first three were worked around in place. This one is
 * not: the schema comes from Flyway and the database is the deployed version,
 * which is what a cross-service seam deserves.
 */
@DataJpaTest
// replace = NONE: this runs against a REAL MySQL, not H2. See the class note.
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ImportAutoConfiguration(FlywayAutoConfiguration.class)
@Import({RunScopeService.class, RunScopeServiceTest.Beans.class})
class ScopeFixtureIT {

    private static final String TENANT = "acme";
    private static final Long PROJECT = 9L;

    @Autowired
    private RunScopeService scopes;
    @Autowired
    private AgentRepository agents;
    @Autowired
    private AgentRunRepository runs;
    @Autowired
    private JdbcTemplate jdbc;
    @Autowired
    private TestEntityManager entities;

    private final ObjectMapper mapper = new ObjectMapper();
    private Long runId;

    private static MySqlTestDatabase database;

    @DynamicPropertySource
    static void datasource(DynamicPropertyRegistry registry) throws Exception {
        database = MySqlTestDatabase.start();
        registry.add("spring.datasource.url", database::url);
        registry.add("spring.datasource.username", database::user);
        registry.add("spring.datasource.password", database::password);
        // The hermetic test profile pins the H2 driver; without this the
        // MySQL URL is handed to org.h2.Driver and rejected.
        registry.add("spring.datasource.driver-class-name",
                () -> "com.mysql.cj.jdbc.Driver");
        registry.add("spring.flyway.enabled", () -> true);
        registry.add("spring.jpa.hibernate.ddl-auto", () -> "none");
    }

    @AfterAll
    static void release() throws Exception {
        database.close();
    }

    @BeforeEach
    void setUp() {
        // No hand-built tables: Flyway built this schema, so agent_run_subject
        // is the real one with the real key.
        jdbc.update("DELETE FROM agent_run_subject");
        jdbc.update("DELETE FROM agent_runs");
        jdbc.update("DELETE FROM agents");

        Agent agent = new Agent();
        agent.setTenantId(TENANT);
        agent.setProjectId(PROJECT);
        agent.setName("aws.public_exposure_auditor");
        Long agentId = agents.save(agent).getId();

        AgentRun run = new AgentRun();
        run.setTenantId(TENANT);
        run.setProjectId(PROJECT);
        run.setAgentId(agentId);
        run.setInput("{}");
        run.setStatus(AgentRun.Status.RUNNING);
        run.setStartedAt(Instant.now());
        runId = runs.save(run).getId();
    }

    private JsonNode fixture(String name) {
        try (var stream = new ClassPathResource("scope-fixtures/" + name + ".json")
                .getInputStream()) {
            return mapper.readTree(stream);
        } catch (Exception e) {
            throw new AssertionError("fixture " + name + " is missing or unreadable", e);
        }
    }

    /**
     * What agent-service will do for real: declare from the agent's static kinds,
     * then complete from the runtime's per-kind claim.
     */
    private void roundTrip(String name, String... declaredKinds) {
        JsonNode payload = fixture(name);

        // The DECLARATION comes from the agent's own tool declarations, not from
        // results — it is knowable at run start and does not vary with which
        // tool happened to run first.
        var intent = mapper.createArrayNode();
        for (String kind : declaredKinds) {
            intent.addObject().put("kind", "all").put("subject_kind", kind);
        }
        scopes.declare(runId, intent, Map.of());
        entities.flush();
        entities.clear();

        scopes.complete(runId, payload.get("subject_scope"),
                subjectIds(payload), evaluated(payload), 0);
        entities.flush();
        entities.clear();
    }

    private Map<String, List<String>> subjectIds(JsonNode payload) {
        Map<String, List<String>> out = new LinkedHashMap<>();
        payload.get("subject_ids").fields().forEachRemaining(entry -> {
            List<String> ids = new ArrayList<>();
            entry.getValue().forEach(id -> ids.add(id.asText()));
            out.put(entry.getKey(), ids);
        });
        return out;
    }

    /** The runtime examined exactly the subjects it enumerated. */
    private Map<String, Integer> evaluated(JsonNode payload) {
        Map<String, Integer> out = new LinkedHashMap<>();
        payload.get("subject_scope").forEach(element ->
                out.put(element.get("subject_kind").asText(),
                        element.get("subject_id_count").asInt()));
        return out;
    }

    private RunScope stored() {
        try {
            return RunScope.parse(mapper.readTree(
                    runs.findById(runId).orElseThrow().getSubjectScope()));
        } catch (Exception e) {
            throw new AssertionError(e);
        }
    }

    // ------------------------------------------------------------ the three ---

    @Test
    void twoKindsBothCompleteRoundTrip() {
        assertThatCode(() -> roundTrip("two-kinds-complete", "cloud_resource", "principal"))
                .doesNotThrowAnyException();

        AgentRun run = runs.findById(runId).orElseThrow();
        assertThat(run.getScopeStatus()).isEqualTo(AgentRun.ScopeStatus.COMPLETE);
        assertThat(stored().reapable())
                .extracting(ScopeClaim::subjectKind)
                .containsExactlyInAnyOrder("cloud_resource", "principal");
    }

    /**
     * <b>The shape the whole per-element design exists for.</b>
     *
     * <p>The elastic IP listing threw; the volume listing did not. The volumes
     * this run really saw keep their coverage, {@code cloud_resource} drops to
     * PARTIAL so nothing reaps an elastic IP finding on evidence that never
     * looked at an elastic IP, and {@code principal} is untouched by a failure
     * in a different kind.
     */
    @Test
    void oneKindPartialKeepsWhatWasSeenAndDoesNotCostTheOther() {
        roundTrip("one-kind-partial", "cloud_resource", "principal");

        AgentRun run = runs.findById(runId).orElseThrow();
        assertThat(run.getScopeStatus())
                .as("mixed, not failed — one kind still has real coverage")
                .isEqualTo(AgentRun.ScopeStatus.PARTIAL);
        assertThat(run.hasUsableCoverage()).isTrue();

        assertThat(stored().reapable())
                .as("only the kind that completed may ground a reap")
                .extracting(ScopeClaim::subjectKind)
                .containsExactly("principal");

        assertThat(jdbc.queryForObject(
                "SELECT COUNT(*) FROM agent_run_subject WHERE run_id = ? AND subject_kind = ?",
                Integer.class, runId, "cloud_resource"))
                .as("the volumes it did enumerate are still materialised")
                .isEqualTo(2);
    }

    @Test
    void oneKindSkippedClaimsNothingForThatKind() {
        roundTrip("one-kind-skipped", "cloud_resource", "principal");

        assertThat(stored().reapable())
                .extracting(ScopeClaim::subjectKind)
                .containsExactly("cloud_resource");
        assertThat(jdbc.queryForObject(
                "SELECT COUNT(*) FROM agent_run_subject WHERE run_id = ? AND subject_kind = ?",
                Integer.class, runId, "principal"))
                .isZero();
    }

    // ------------------------------------------------------ the digest seam ---

    /**
     * Python computed these digests; Java recomputes them from the same ids.
     *
     * <p>{@link RunScopeService#declare} refuses a scope whose digest does not
     * match the subjects sent beside it, so every round trip above already
     * depends on this. Asserted separately because a silent agreement is
     * indistinguishable from a silent absence of checking — if the fixtures
     * were ever regenerated with a changed canonical form, the round trips would
     * fail with a message about digests and nobody would know which side moved.
     */
    @Test
    void theDigestsInTheFixturesWereComputedTheSameWayOnBothSides() {
        JsonNode payload = fixture("two-kinds-complete");

        payload.get("subject_scope").forEach(element -> {
            String kind = element.get("subject_kind").asText();
            List<String> ids = subjectIds(payload).get(kind);
            assertThat(com.intertec.autoops.agent.scope.SubjectDigest.digest(ids))
                    .as("digest for %s", kind)
                    .isEqualTo(element.get("subject_ids_digest").asText());
        });
    }

    // ----------------------------------------------------- the seam's guard ---

    /**
     * The rejection that would have broken every correlator, confirmed against
     * real runtime output rather than hand-written JSON.
     *
     * <p>If the declaration were built from results seen so far, the exposure
     * auditor would declare {@code cloud_resource} after its first two tools and
     * complete with {@code principal} as well. This is what that looks like from
     * agent-service: refused, and the run marked FAILED with the reason kept.
     */
    @Test
    void aCompletionNamingAKindTheRunNeverDeclaredIsRefused() {
        JsonNode payload = fixture("two-kinds-complete");

        var narrowIntent = mapper.createArrayNode();
        narrowIntent.addObject().put("kind", "all").put("subject_kind", "cloud_resource");
        scopes.declare(runId, narrowIntent, Map.of());
        entities.flush();
        entities.clear();

        assertThatThrownBy(() -> scopes.complete(runId, payload.get("subject_scope"),
                subjectIds(payload), evaluated(payload), 0))
                .isInstanceOf(AgentException.class)
                .hasMessageContaining("never set out to cover");

        // flush BEFORE clear: clear() discards pending changes rather than
        // writing them, so clearing alone would throw away the very FAILED
        // record this asserts. In production markFailed commits its own
        // transaction — see the note on RunScopeService.complete.
        entities.flush();
        entities.clear();
        assertThat(runs.findById(runId).orElseThrow().getScopeStatus())
                .isEqualTo(AgentRun.ScopeStatus.FAILED);
    }
}
